<br/>
<nav class="navbar navbar-expand-lg  navbar-light style="background-color: #fbc7d4;"">
    <a class="navbar-brand" href="index.php">MusicPlayer</a>

    <ul class="navbar-nav mr-auto">
         <li class="nav-item active">
            <a class="nav-link" href=""> Cadastrar:
                <span class="sr-only">(current)</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="form_genero.php"> G&ecircnero </a>
        </li>   
        <li class="nav-item">
            <a class="nav-link" href="form_banda.php"> Banda </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="form_musica.php"> M&uacutesica </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="form_playlist.php"> Playlist </a>
        </li>   
        <li class="nav-item active">
            <a class="nav-link" href=""> Listar:
                <span class="sr-only">(current)</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="genero.php"> G&ecircnero </a>
        </li>  
        <li class="nav-item">
            <a class="nav-link" href="banda.php"> Banda </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="musica.php"> M&uacutesica </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="playlist.php"> Playlist </a>
        </li>       
    </ul>
</nav>
